// app/layout.tsx or app/RootLayout.tsx
import Navbar from "./components/NavBar"; // Adjust the path if necessary
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Raprast | Engineer & Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`"font-custom" antialiased`} style={{background: '#1E1E2E'}}>
        <Navbar />
        {children} {/* This renders the content of your pages */}
      </body>
    </html>
  );
}
